"""H32 · music.* on an in-process mpvd with a music folder generated by ffmpeg: default XDG folder added once, scan
(incremental), artists › albums › tracks, genres, years, accent-insensitive search, covers (folder image and embedded
picture extracted to the cache), ReplayGain 2.0 computed in the background for tracks without tags (track and album
gain, stored in the index, the files untouched), music.gain for files outside the library (artifact cache), M3U8
playlists (create, add, move, remove, sort, rename, import/export, trash), smart lists and the local history."""

from __future__ import annotations

import asyncio
import math
import os
import shutil
import time
from pathlib import Path

import pytest

from mpvd.client import MpvdClient
from mpvd.config import Settings
from mpvd.music import tags as tagmod
from mpvd.music.playlists import format_m3u, parse_m3u
from mpvd.rpc import RpcError
from mpvd.server import MpvdServer
from tests.music_helpers import build_music, tone


@pytest.fixture(scope="module")
def music_src(tmp_path_factory) -> tuple[Path, dict[str, Path]]:
    root = tmp_path_factory.mktemp("music-src")
    return root, build_music(root / "Música")


@pytest.fixture
def music(tmp_path, music_src) -> tuple[Path, dict[str, Path]]:
    """A private copy (tests rename/touch files)."""
    src_root, files = music_src
    dest = tmp_path / "Música"
    shutil.copytree(src_root / "Música", dest)
    return dest, {k: dest / v.relative_to(src_root / "Música") for k, v in files.items()}


@pytest.fixture
def settings(tmp_path):
    return Settings(runtime_dir=tmp_path / "rt", cache_dir=tmp_path / "cache", data_dir=tmp_path / "data",
                    idle_timeout=0, workers=2)


def run(settings: Settings, fn):
    async def go():
        server = MpvdServer(settings)
        await server.start()
        try:
            async with MpvdClient(str(settings.socket_path)) as c:
                return await fn(c, server)
        finally:
            await server.stop()

    return asyncio.run(go())


async def wait_for(pred, timeout: float = 60.0):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        v = await pred()
        if v:
            return v
        await asyncio.sleep(0.1)
    raise TimeoutError("condition not met")


def test_parse_probe_and_ebur128_pure():
    data = {"format": {"duration": "12.5", "tags": {"ARTIST": "A", "album_artist": "AA", "ALBUM": "X", "DATE": "1999-02",
                                                    "GENRE": "Rock, Pop; (17)", "track": "03/10", "disc": "2/2",
                                                    "REPLAYGAIN_TRACK_GAIN": "-6.54 dB"}},
            "streams": [{"codec_type": "audio", "codec_name": "vorbis", "tags": {"TITLE": "T", "ARTIST": "ignored"}},
                        {"codec_type": "video", "disposition": {"attached_pic": 1}}]}
    m = tagmod.parse_probe(data, "/x/y.ogg")
    assert (m["title"], m["artist"], m["album_artist"], m["album"], m["year"]) == ("T", "A", "AA", "X", 1999)
    assert m["genres"] == ["Rock", "Pop"] and (m["track_no"], m["disc_no"]) == (3, 2)
    assert m["tag_track_gain"] == -6.54 and m["has_pic"] and m["duration"] == 12.5
    bare = tagmod.parse_probe({"format": {}, "streams": [{"codec_type": "audio"}]}, "/m/Canción.flac")
    assert bare["title"] == "Canción" and bare["artist"] == "" and bare["genres"] == []

    err = ("  Integrated loudness:\n    I:         -27.8 LUFS\n    Threshold: -37.8 LUFS\n\n"
           "  Sample peak:\n    Peak:      -24.1 dBFS\n")
    r = tagmod.parse_ebur128(err)
    assert r["gain"] == 9.8 and r["loudness"] == -27.8 and abs(r["peak"] - 10 ** (-24.1 / 20)) < 1e-5
    with pytest.raises(ValueError):
        tagmod.parse_ebur128("  Integrated loudness:\n    I:         -inf LUFS\n")
    # album: energy mean weighted by duration (a quiet short track barely moves it)
    g, pk = tagmod.album_gain([(-20.0, 100, 0.5), (-30.0, 10, 0.9)])
    expect = -18 - 10 * math.log10((100 * 10 ** -2 + 10 * 10 ** -3) / 110)
    assert abs(g - round(expect, 2)) < 0.011 and pk == 0.9


def test_m3u_roundtrip(tmp_path):
    entries = [{"path": "/música/a b.flac", "title": "Artista - Título", "duration": 61.4},
               {"path": "https://radio.example/stream", "title": "", "duration": -1}]
    text = format_m3u("Mi lista", entries)
    assert text.startswith("#EXTM3U\n#PLAYLIST:Mi lista\n#EXTINF:61,Artista - Título\n/música/a b.flac\n")
    name, back = parse_m3u(text)
    assert name == "Mi lista" and [e["path"] for e in back] == [e["path"] for e in entries]
    assert back[0]["title"] == "Artista - Título" and back[0]["duration"] == 61
    # plain M3U with relative paths and a file:// URL
    _, rel = parse_m3u("uno.mp3\n\n# comentario\nsub/dos.flac\nfile:///abs/tres%20t.ogg\n", tmp_path)
    assert [e["path"] for e in rel] == [str(tmp_path / "uno.mp3"), str(tmp_path / "sub" / "dos.flac"), "/abs/tres t.ogg"]


def test_default_folder_scan_browse_search_covers_replaygain(settings, music, monkeypatch):
    root, p = music
    monkeypatch.setenv("MPV_UOS_MUSIC_DIR", str(root))
    before = {f: f.read_bytes() for f in p.values()}

    async def go(c, server):
        caps = await c.call("capabilities")
        assert caps["services"]["music"] is True
        assert {"music.status", "music.album", "music.smart", "music.playlists.move", "music.gain"} <= {
            m["name"] for m in caps["methods"]}
        st = await c.call("music.status")          # first open: the XDG Music folder is added and scanned
        assert st["default_folder"] == str(root)
        folders = await c.call("music.folders.list")
        assert [f["path"] for f in folders] == [str(root)]
        assert server.music.scan_job is not None and server.music.scan_job.priority.name == "INDEX"
        await server.music.scan_job.wait(60)
        assert server.music.scan_job.result["added"] == 5, server.music.scan_job.result
        # ReplayGain follows the scan in the background (auto_replaygain on by default)
        await wait_for(lambda: _rg_done(c), 90)
        st = await c.call("music.status")
        assert (st["tracks"], st["albums"], st["artists"], st["genres"]) == (5, 3, 4, 3), st
        assert st["replaygain"]["tags"] == 1 and st["replaygain"]["done"] == 4 and st["replaygain"]["pending"] == 0
        assert server.music.rg_job.priority.name == "INDEX" and server.music.rg_job.heavy

        # removing the default folder is respected: it is never added again
        await c.call("music.folders.remove", {"path": str(root)})
        assert (await c.call("music.status"))["tracks"] == 0
        assert await c.call("music.folders.list") == []
        await c.call("music.folders.add", {"path": str(root), "scan": False})
        res = await c.call("music.scan", {"wait": True})
        assert res["result"]["added"] == 5
        measured = server.music.measure
        server.music.measure = None           # re-added files: loudness comes from the cache, nothing is decoded
        await wait_for(lambda: _rg_done(c), 30)
        server.music.measure = measured
        res = await c.call("music.scan", {"wait": True})     # incremental: nothing probed again
        assert (res["result"]["added"], res["result"]["unchanged"]) == (0, 5)

        artists = await c.call("music.artists")
        assert [a["name"] for a in artists] == ["Héroes del Silencio", "Mónica Naranjo", "Otro", "Artista desconocido"]
        mon = artists[1]
        view = await c.call("music.artist", {"key": mon["key"]})
        assert [a["title"] for a in view["albums"]] == ["Palabra de mujer"] and view["albums"][0]["year"] == 1997
        unknown = await c.call("music.artist", {"key": ""})
        assert [a["title"] for a in unknown["albums"]] == ["Sin álbum"] and unknown["tracks"] == 1

        albums = await c.call("music.albums")
        assert [a["title"] for a in albums] == ["Con ganancia", "Palabra de mujer", "Senderos"]
        pdm = albums[1]
        assert pdm["cover"] == str(p["t1"].parent / "cover.jpg") and pdm["tracks"] == 2
        sen = albums[2]
        assert sen["cover"].startswith(str(settings.cache_dir)) and Path(sen["cover"]).stat().st_size > 100

        alb = await c.call("music.album", {"key": pdm["key"]})
        assert [t["label"] for t in alb["tracks"]] == ["1. Sobreviviré", "2. Desátame"]
        t1, t2 = alb["tracks"]
        # computed ReplayGain 2.0: the quiet track gets ~12 dB more than the loud one (−3 vs −15 dB tones)
        assert t1["gain"] is not None and 10.5 < t2["gain"] - t1["gain"] < 13.5, (t1["gain"], t2["gain"])
        assert t1["album_gain"] is not None and t1["gain"] <= t1["album_gain"] <= t2["gain"]
        assert not t1["has_tags"] and t1["cover"].endswith("cover.jpg")

        genres = await c.call("music.genres")
        assert [(g["name"], g["tracks"]) for g in genres] == [("Balada", 2), ("Pop", 2), ("Rock", 2)]
        assert [a["title"] for a in await c.call("music.albums", {"genre": "rock"})] == ["Con ganancia", "Senderos"]
        years = await c.call("music.years")
        assert [y["year"] for y in years] == [2010, 1997, 1985]

        res = await c.call("music.search", {"q": "monica"})
        assert [a["name"] for a in res["artists"]] == ["Mónica Naranjo"] and len(res["tracks"]) == 2
        res = await c.call("music.search", {"q": "desatame"})
        assert [t["title"] for t in res["tracks"]] == ["Desátame"] and res["artists"] == []
        res = await c.call("music.search", {"q": "heroes senderos"})
        assert [a["title"] for a in res["albums"]] == ["Senderos"]
        res = await c.call("music.search", {"q": "sin etiquetas"})
        assert [t["title"] for t in res["tracks"]] == ["pista sin etiquetas"]
        assert res["tracks"][0]["artist"] == "Artista desconocido"

        g = await c.call("music.gain", {"path": str(p["tagged"])})
        assert g["has_tags"] is True and g["gain"] is None           # mpv applies the tag itself
        g = await c.call("music.gain", {"path": str(p["t2"])})
        assert g["indexed"] and g["gain"] == t2["gain"] and g["album_gain"] == t2["album_gain"]
        cov = await c.call("music.cover", {"path": str(p["emb"])})
        assert cov["cover"] == sen["cover"]
        return True

    assert run(settings, go)
    assert {f: f.read_bytes() for f in p.values()} == before       # never rewrites the user's files


async def _rg_done(c):
    st = await c.call("music.status", {"default_folder": False})
    rg = st["replaygain"]
    return st["tracks"] > 0 and rg["pending"] == 0 and not rg["running"] and not st["scanning"]


def test_gain_outside_library_is_cached_and_measured_once(settings, tmp_path, monkeypatch):
    monkeypatch.setenv("MPV_UOS_MUSIC_DIR", "")
    f = tone(tmp_path / "fuera.flac", 440, 3, -10, {"title": "Fuera"})
    calls = []

    async def go(c, server):
        real = server.music.measure

        def counting(path):
            calls.append(path)
            return real(path)

        server.music.measure = counting
        st = await c.call("music.status")
        assert st["default_folder"] == "" and await c.call("music.folders.list") == []
        g1 = await c.call("music.gain", {"path": str(f)})
        g2 = await c.call("music.gain", {"path": "file://" + str(f)})
        assert g1["indexed"] is False and g1["gain"] is not None and g1 == g2
        assert (await c.call("music.gain", {"path": "https://example.com/a.mp3"}))["gain"] is None
        return True

    assert run(settings, go)
    assert calls == [str(f)]


def test_playlists_smart_lists_and_history(settings, music, tmp_path, monkeypatch):
    root, p = music
    monkeypatch.setenv("MPV_UOS_MUSIC_DIR", "")

    async def go(c, server):
        await c.call("music.folders.add", {"path": str(root), "scan": False})
        await c.call("music.settings.set", {"auto_replaygain": False})
        assert (await c.call("music.settings.get")) == {"auto_replaygain": False}
        await c.call("music.scan", {"wait": True})
        assert (await c.call("music.status"))["replaygain"]["pending"] == 4   # nothing measured while off

        # create / add / insert / move / remove / sort
        pl = await c.call("music.playlists.create", {"name": "Para correr", "paths": [str(p["t1"]), str(p["emb"])]})
        assert [t["title"] for t in pl["tracks"]] == ["Sobreviviré", "Entre dos tierras"]
        with pytest.raises(RpcError):
            await c.call("music.playlists.create", {"name": "Para correr"})
        pl = await c.call("music.playlists.add", {"name": "Para correr", "paths": [str(p["loose"])], "position": 0})
        assert [t["title"] for t in pl["tracks"]] == ["pista sin etiquetas", "Sobreviviré", "Entre dos tierras"]
        pl = await c.call("music.playlists.move", {"name": "Para correr", "src": 0, "dst": 2})
        assert [t["title"] for t in pl["tracks"]] == ["Sobreviviré", "Entre dos tierras", "pista sin etiquetas"]
        pl = await c.call("music.playlists.add", {"name": "Para correr", "paths": [str(p["t2"])]})
        pl = await c.call("music.playlists.sort", {"name": "Para correr", "by": "artist"})
        assert [t["title"] for t in pl["tracks"]] == ["Entre dos tierras", "Sobreviviré", "Desátame",
                                                      "pista sin etiquetas"]
        pl = await c.call("music.playlists.remove", {"name": "Para correr", "index": [0, 3]})
        assert [t["title"] for t in pl["tracks"]] == ["Sobreviviré", "Desátame"] and pl["duration"] == 8

        f = Path(pl["file"])
        assert f.parent == settings.data_dir / "music" / "playlists" and f.name == "Para correr.m3u8"
        text = f.read_text(encoding="utf-8")
        assert text.startswith("#EXTM3U\n#PLAYLIST:Para correr\n#EXTINF:4,Mónica Naranjo - Sobreviviré\n" + str(p["t1"]))

        # rename, export (relative), import it back, delete to the trash
        pl = await c.call("music.playlists.rename", {"name": "Para correr", "new_name": "Correr"})
        assert pl["name"] == "Correr" and not f.exists()
        out = tmp_path / "export"
        out.mkdir()
        res = await c.call("music.playlists.export", {"name": "Correr", "path": str(out), "relative": True})
        exported = Path(res["path"])
        assert exported == out / "Correr.m3u8"
        assert os.path.relpath(p["t1"], out) in exported.read_text(encoding="utf-8")
        imp = await c.call("music.playlists.import", {"path": str(exported)})
        assert imp["name"] == "Correr (2)" and [t["path"] for t in imp["tracks"]] == [str(p["t1"]), str(p["t2"])]
        names = [x["name"] for x in await c.call("music.playlists.list")]
        assert names == ["Correr", "Correr (2)"]
        res = await c.call("music.playlists.delete", {"name": "Correr (2)"})
        assert Path(res["trash"]).exists() and ".papelera" in res["trash"]
        assert [x["name"] for x in await c.call("music.playlists.list")] == ["Correr"]
        with pytest.raises(RpcError):
            await c.call("music.playlists.get", {"name": "Correr (2)"})

        # history → smart lists
        for path in (p["t2"], p["t2"], p["emb"]):
            assert (await c.call("music.played", {"path": str(path), "seconds": 4}))["indexed"] is True
        other = tone(tmp_path / "otra.mp3", 300, 2, -6, {})
        assert (await c.call("music.played", {"path": str(other), "seconds": 2, "title": "Otra"}))["indexed"] is False
        hist = await c.call("music.history")
        assert [h["title"] for h in hist] == ["Otra", "Entre dos tierras", "Desátame", "Desátame"]
        top = await c.call("music.smart", {"kind": "top"})
        assert [(t["title"], t["plays"]) for t in top["tracks"]] == [("Desátame", 2), ("Entre dos tierras", 1)]
        unplayed = await c.call("music.smart", {"kind": "unplayed"})
        assert {t["title"] for t in unplayed["tracks"]} == {"Sobreviviré", "Etiquetada", "pista sin etiquetas"}
        recent = await c.call("music.smart", {"kind": "recent", "limit": 2})
        assert len(recent["tracks"]) == 2
        genre = await c.call("music.smart", {"kind": "genre", "value": "Balada"})
        assert genre["title"] == "Balada" and [t["title"] for t in genre["tracks"]] == ["Sobreviviré", "Desátame"]
        dec = await c.call("music.smart", {"kind": "decade", "value": 1990})
        assert dec["title"] == "Años 90" and len(dec["tracks"]) == 2
        year = await c.call("music.smart", {"kind": "year", "value": 1985})
        assert [t["title"] for t in year["tracks"]] == ["Entre dos tierras"]
        lists = await c.call("music.smart")
        assert [x["kind"] for x in lists][:3] == ["recent", "top", "unplayed"]
        assert [x["title"] for x in lists if x["kind"] == "decade"] == ["Años 10", "Años 90", "Años 80"]
        t = await c.call("music.track", {"path": str(p["t2"])})
        assert t["plays"] == 2 and t["indexed"]
        assert (await c.call("music.history.clear"))["removed"] == 4
        assert await c.call("music.history") == []
        return True

    assert run(settings, go)
