#!/usr/bin/env bash
# User install on Linux (no sudo): launcher in ~/.local/bin, desktop entry + icon under $XDG_DATA_HOME, optional default player.
# The checkout stays where it is (the launcher points to it); ~/.config/mpv is never touched.
# Usage: tools/install.sh [--xdg] [--extras] [--no-sync] [--no-vendor] [--default] [--dry-run]
#        tools/install.sh --uninstall [--dry-run]
# Env:   MPV_UOS_BIN_DIR (default ~/.local/bin), XDG_DATA_HOME (default ~/.local/share).
set -euo pipefail
ROOT="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
BIN_DIR="${MPV_UOS_BIN_DIR:-$HOME/.local/bin}"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
APPS_DIR="$DATA_HOME/applications"
ICON_DIR="$DATA_HOME/icons/hicolor/scalable/apps"
LAUNCHER="$BIN_DIR/mpv-uos"
DESKTOP="$APPS_DIR/mpv-uos.desktop"
ICON="$ICON_DIR/mpv-uos.svg"
MARK="# generated by MPV-UOS tools/install.sh"
MIME="application/ogg;application/x-ogg;application/mxf;application/sdp;application/smil;audio/aac;audio/x-aac;audio/aiff;audio/x-aiff;\
audio/m4a;audio/x-m4a;audio/mp3;audio/x-mp3;audio/mpeg;audio/mpegurl;audio/x-mpegurl;audio/ogg;audio/scpls;audio/x-scpls;audio/wav;\
audio/x-wav;audio/x-ms-wma;audio/flac;audio/mp4;audio/opus;audio/webm;audio/x-matroska;audio/ac3;audio/eac3;audio/vnd.wave;\
audio/x-vorbis+ogg;video/mpeg;video/mp4;video/x-m4v;video/ogg;video/quicktime;video/x-msvideo;video/avi;video/vnd.avi;video/x-flv;\
video/x-matroska;video/mkv;video/webm;video/x-ms-wmv;video/x-ms-asf;video/mp2t;video/3gpp;video/3gpp2;video/dv;\
application/x-matroska;application/x-mpegurl;application/vnd.apple.mpegurl;video/vnd.mpegurl;"

XDG=0 EXTRAS=0 SYNC=1 VENDOR=1 DEFAULT=0 DRY=0 UNINSTALL=0
for arg in "$@"; do
  case "$arg" in
    --xdg) XDG=1 ;;             # cache/data in ~/.cache/mpv-uos and ~/.local/share/mpv-uos instead of <checkout>/.cache
    --extras) EXTRAS=1 ;;       # also install the optional translate + semantic extras (~220 MB)
    --no-sync) SYNC=0 ;;
    --no-vendor) VENDOR=0 ;;
    --default) DEFAULT=1 ;;     # make MPV-UOS the default app for the video/audio MIME types (xdg-mime)
    --dry-run) DRY=1 ;;
    --uninstall) UNINSTALL=1 ;;
    -h|--help) sed -n '2,7p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "opción desconocida: $arg" >&2; exit 2 ;;
  esac
done

say() { printf '• %s\n' "$*"; }
run() { if [ "$DRY" = 1 ]; then printf '  (dry-run) %s\n' "$*"; else "$@"; fi; }
ours() { [ -f "$1" ] && grep -qF "$MARK" "$1"; }

refresh_caches() {
  if command -v update-desktop-database >/dev/null 2>&1; then run update-desktop-database -q "$APPS_DIR" || true; fi
  if command -v gtk-update-icon-cache >/dev/null 2>&1 && [ -f "$DATA_HOME/icons/hicolor/index.theme" ]; then
    run gtk-update-icon-cache -q -t "$DATA_HOME/icons/hicolor" || true
  fi
}

if [ "$UNINSTALL" = 1 ]; then
  # Only remove files this script created (marker line); anything else with the same name is left alone.
  for f in "$LAUNCHER" "$DESKTOP"; do
    if ours "$f"; then say "borrando $f"; run rm -f "$f"
    elif [ -e "$f" ]; then say "no es de MPV-UOS, se deja: $f"; fi
  done
  if [ -f "$ICON" ] && grep -qF "MPV-UOS" "$ICON"; then say "borrando $ICON"; run rm -f "$ICON"; fi
  refresh_caches
  say "desinstalado (el checkout, .cache/ y los datos de usuario no se tocan)"
  exit 0
fi

# -- requirements -----------------------------------------------------------------------------------------
missing=()
command -v mpv >/dev/null 2>&1 || missing+=("mpv (≥ 0.41)")
command -v ffmpeg >/dev/null 2>&1 || missing+=("ffmpeg")
command -v ffprobe >/dev/null 2>&1 || missing+=("ffprobe")
if [ "$SYNC" = 1 ]; then command -v uv >/dev/null 2>&1 || missing+=("uv (https://docs.astral.sh/uv/)"); fi
if [ ${#missing[@]} -gt 0 ]; then
  printf 'Faltan: %s\n' "${missing[@]}" >&2
  echo "Debian/Ubuntu: sudo apt install mpv ffmpeg  ·  uv: curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
  exit 1
fi
ver="$(mpv --version 2>/dev/null | sed -n '1s/^mpv v\{0,1\}\([0-9]*\)\.\([0-9]*\).*/\1 \2/p' || true)"
if [ -n "$ver" ]; then
  read -r major minor <<<"$ver"
  if [ "$major" -eq 0 ] && [ "$minor" -lt 41 ]; then say "aviso: mpv $major.$minor < 0.41; algunas funciones no irán"; fi
fi

# -- python env + vendored third parties ------------------------------------------------------------------
if [ "$SYNC" = 1 ]; then
  if [ "$EXTRAS" = 1 ]; then say "uv sync (con extras translate + semantic)"; run uv sync --project "$ROOT" --extra translate --extra semantic
  else say "uv sync"; run uv sync --project "$ROOT"; fi
fi
if [ "$VENDOR" = 1 ]; then say "tools/vendor.sh (uosc, thumbfast, yt-dlp)"; run "$ROOT/tools/vendor.sh"; fi

# -- launcher -----------------------------------------------------------------------------------------------
if [ -e "$LAUNCHER" ] && ! ours "$LAUNCHER"; then
  echo "Ya existe $LAUNCHER y no lo creó MPV-UOS: no se sobrescribe (bórralo o usa MPV_UOS_BIN_DIR)." >&2
  exit 1
fi
say "lanzador $LAUNCHER → $ROOT/bin/mpv-uos"
env_lines=""
if [ "$XDG" = 1 ]; then
  env_lines='export MPV_UOS_CACHE_DIR="${MPV_UOS_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/mpv-uos}"
export MPV_UOS_DATA_DIR="${MPV_UOS_DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/mpv-uos}"'
fi
if [ "$DRY" = 0 ]; then
  mkdir -p "$BIN_DIR"
  cat >"$LAUNCHER" <<EOF
#!/usr/bin/env bash
$MARK
$env_lines
exec "$ROOT/bin/mpv-uos" "\$@"
EOF
  chmod 755 "$LAUNCHER"
fi

# -- desktop entry + icon -------------------------------------------------------------------------------------
say "entrada de escritorio $DESKTOP"
if [ "$DRY" = 0 ]; then
  mkdir -p "$APPS_DIR" "$ICON_DIR"
  sed 's|<svg |<svg data-app="MPV-UOS" |' "$ROOT/mpvd/remote/www/icon.svg" >"$ICON"
  cat >"$DESKTOP" <<EOF
[Desktop Entry]
$MARK
Type=Application
Name=MPV-UOS
GenericName=Reproductor multimedia
Comment=mpv + uosc con subtítulos IA, TV y radio, yt-dlp y mando desde el móvil
Icon=mpv-uos
TryExec=$LAUNCHER
Exec=$LAUNCHER --player-operation-mode=pseudo-gui --wayland-app-id=mpv-uos --x11-name=mpv-uos -- %U
Terminal=false
Categories=AudioVideo;Audio;Video;Player;TV;
MimeType=$MIME
X-KDE-Protocols=file,ftp,hls,http,https,mms,rtmp,rtmps,rtp,rtsp,rtsps,sftp,srt,webdav,webdavs
StartupWMClass=mpv-uos
Keywords=mpv;uosc;media;player;video;audio;tv;radio;subtitles;
EOF
  if command -v desktop-file-validate >/dev/null 2>&1; then desktop-file-validate "$DESKTOP"; fi
fi
refresh_caches

if [ "$DEFAULT" = 1 ]; then
  if command -v xdg-mime >/dev/null 2>&1; then
    say "MPV-UOS como reproductor por defecto (xdg-mime)"
    IFS=';' read -r -a types <<<"$MIME"
    run xdg-mime default mpv-uos.desktop "${types[@]}"
  else
    say "xdg-mime no está: no se cambia el reproductor por defecto"
  fi
fi

case ":$PATH:" in *":$BIN_DIR:"*) ;; *) say "aviso: $BIN_DIR no está en PATH (añádelo en ~/.profile)";; esac
say "listo: 'mpv-uos <archivo|URL>' o busca MPV-UOS en el menú de aplicaciones. Desinstalar: tools/install.sh --uninstall"
