# User install on Windows (no administrator rights): the PowerShell twin of tools/install.sh.
# The checkout stays where it is (everything points to it); nothing is written to the system or to %APPDATA%\mpv.
#   - checks mpv/ffmpeg/ffprobe/uv on PATH (mpv >= 0.41), runs `uv sync`
#   - vendors the Windows binaries pinned in vendor.lock, each verified with SHA-256: ziggy-windows.exe (uosc),
#     yt-dlp.exe (checked against SHA2-256SUMS of the same release), deno.exe (only without deno / node >= 22),
#     and with -Whisper the official whisper.cpp CPU build (whisper-cli.exe + DLLs)
#   - %LOCALAPPDATA%\MPV-UOS\bin\mpv-uos.cmd, a Start menu shortcut and the mpv-uos:// links (HKCU\Software\Classes)
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File tools\install.ps1 [-Extras] [-Whisper] [-NoSync]
#          [-NoVendor] [-NoProtocol] [-Force] [-InstallDir <dir>] [-DryRun]
#        powershell -NoProfile -ExecutionPolicy Bypass -File tools\install.ps1 -Uninstall [-DryRun]
#        (GNU spellings work too: --uninstall, --dry-run, --no-sync, --no-vendor, --whisper, --extras, --no-protocol)
# Env:   MPV_UOS_INSTALL_DIR (default %LOCALAPPDATA%\MPV-UOS), MPV_UOS_START_MENU_DIR (default: the user's Programs
#        folder of the Start menu), MPV_UOS_VENDOR_LOCK (default <checkout>\vendor.lock), MPV_UOS_YTDLP_BASE_URL.
# -DryRun changes nothing and ends with one JSON line: {"mode": ..., "actions": [{"action","target","detail"}...]}.
# User data (%APPDATA%\mpv-uos) and the checkout are never removed by -Uninstall.
# Works with Windows PowerShell 5.1 and PowerShell 7 (no 7-only syntax); tested only with pwsh 7 on Linux.
[CmdletBinding()]
param(
  [switch]$Uninstall,
  [switch]$DryRun,
  [switch]$NoSync,
  [switch]$NoVendor,
  [switch]$Whisper,
  [switch]$Extras,
  [switch]$NoProtocol,
  [switch]$Force,
  [string]$InstallDir = '',
  [Parameter(ValueFromRemainingArguments = $true)][string[]]$Rest
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2.0
$MARK = 'generated by MPV-UOS tools/install.ps1'
$PROTOCOL_KEY = 'HKCU:\Software\Classes\mpv-uos'

function Test-OnWindows {
  return [System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT
}

function Read-MuVendorLock {
  # vendor.lock is KEY=VALUE (sourced by tools/vendor.sh); comments and blank lines are skipped.
  param([string]$Path)
  $lock = @{}
  foreach ($line in [System.IO.File]::ReadAllLines($Path)) {
    $t = $line.Trim()
    if (-not $t -or $t.StartsWith('#')) { continue }
    $i = $t.IndexOf('=')
    if ($i -gt 0) { $lock[$t.Substring(0, $i)] = $t.Substring($i + 1) }
  }
  return $lock
}

function Get-MuLockValue {
  param([hashtable]$Lock, [string]$Key)
  if ($Lock.ContainsKey($Key)) { return [string]$Lock[$Key] }
  return ''
}

function Get-MuSha256 {
  param([string]$Path)
  return (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()
}

function Get-MuSumsEntry {
  # SHA2-256SUMS lines are "<hex>  <name>" (sha256sum format, "*<name>" in binary mode).
  param([string]$Text, [string]$Name)
  foreach ($line in $Text -split "`r?`n") {
    $parts = $line.Trim() -split '\s+'
    if ($parts.Count -ge 2 -and $parts[0] -match '^[0-9a-fA-F]{64}$' -and $parts[-1].TrimStart('*') -eq $Name) {
      return $parts[0].ToLowerInvariant()
    }
  }
  return ''
}

function Invoke-MuDownload {
  param([string]$Url, [string]$Dest)
  $old = $ProgressPreference
  $ProgressPreference = 'SilentlyContinue'   # the progress bar makes Invoke-WebRequest many times slower on 5.1
  try {
    if ($PSVersionTable.PSVersion.Major -lt 6) {
      [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
    }
    $part = "$Dest.part"
    Invoke-WebRequest -UseBasicParsing -Uri $Url -OutFile $part
    Move-Item -Force -LiteralPath $part -Destination $Dest
  } finally {
    $ProgressPreference = $old
  }
}

function Save-MuVerified {
  # Download $Url to $Dest unless a copy with the expected SHA-256 is already there. Returns 'cached' or 'downloaded';
  # throws (and leaves nothing behind) on a hash mismatch.
  param([string]$Url, [string]$Sha256, [string]$Dest)
  if (-not $Sha256) { throw "no SHA-256 pinned for $Url" }
  $Sha256 = $Sha256.ToLowerInvariant()
  if ((Test-Path -LiteralPath $Dest -PathType Leaf) -and (Get-MuSha256 $Dest) -eq $Sha256) { return 'cached' }
  $null = New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Dest)
  $tmp = "$Dest.verify"
  Invoke-MuDownload -Url $Url -Dest $tmp
  $actual = Get-MuSha256 $tmp
  if ($actual -ne $Sha256) {
    Remove-Item -Force -LiteralPath $tmp
    throw "SHA-256 incorrecto para ${Url}: $actual (esperado $Sha256)"
  }
  Move-Item -Force -LiteralPath $tmp -Destination $Dest
  return 'downloaded'
}

function Expand-MuZipEntries {
  # Extract the entries whose full name matches one of $Patterns (-like) into $DestDir, flattened. Returns their names.
  param([string]$Zip, [string[]]$Patterns, [string]$DestDir)
  try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { }
  try { Add-Type -AssemblyName System.IO.Compression.ZipFile } catch { }
  $null = New-Item -ItemType Directory -Force -Path $DestDir
  $names = @()
  $archive = [System.IO.Compression.ZipFile]::OpenRead($Zip)
  try {
    foreach ($e in $archive.Entries) {
      if (-not $e.Name) { continue }
      foreach ($p in $Patterns) {
        if ($e.FullName -like $p) {
          $target = Join-Path $DestDir $e.Name
          [System.IO.Compression.ZipFileExtensions]::ExtractToFile($e, "$target.part", $true)
          Move-Item -Force -LiteralPath "$target.part" -Destination $target
          $names += $e.Name
          break
        }
      }
    }
  } finally {
    $archive.Dispose()
  }
  return $names
}

function Install-MuYtDlp {
  # yt-dlp.exe of the release pinned in vendor.lock (YTDLP_VERSION), verified against that release's SHA2-256SUMS
  # (and against YTDLP_EXE_SHA256 when the lock pins it). Kept if present: mpvd's daily updater may have installed a
  # newer, equally verified build (mpvd/ytdl/binary.py); -Force reinstalls the pinned one.
  param([hashtable]$Lock, [string]$VendorDir, [string]$BaseUrl = '', [switch]$Force)
  $ver = Get-MuLockValue $Lock 'YTDLP_VERSION'
  if (-not $ver) { throw 'vendor.lock has no YTDLP_VERSION' }
  if (-not $BaseUrl) { $BaseUrl = "https://github.com/yt-dlp/yt-dlp/releases/download/$ver" }
  $bin = Join-Path $VendorDir 'bin'
  $exe = Join-Path $bin 'yt-dlp.exe'
  if ((Test-Path -LiteralPath $exe -PathType Leaf) -and -not $Force) { return 'present' }
  $dl = Join-Path $VendorDir 'dl'
  $null = New-Item -ItemType Directory -Force -Path $dl, $bin
  $sumsPath = Join-Path $dl "SHA2-256SUMS-$ver"
  Invoke-MuDownload -Url "$BaseUrl/SHA2-256SUMS" -Dest $sumsPath
  $sha = Get-MuSumsEntry -Text ([System.IO.File]::ReadAllText($sumsPath)) -Name 'yt-dlp.exe'
  if (-not $sha) { throw "SHA2-256SUMS de yt-dlp $ver no tiene yt-dlp.exe" }
  $pinned = Get-MuLockValue $Lock 'YTDLP_EXE_SHA256'
  if ($pinned -and $pinned.ToLowerInvariant() -ne $sha) { throw "SHA2-256SUMS no coincide con YTDLP_EXE_SHA256 de vendor.lock" }
  $cached = Join-Path $dl "yt-dlp-$ver.exe"
  $how = Save-MuVerified -Url "$BaseUrl/yt-dlp.exe" -Sha256 $sha -Dest $cached
  Copy-Item -Force -LiteralPath $cached -Destination $exe
  # same side file as mpvd's updater (<target>.version), no BOM
  [System.IO.File]::WriteAllText("$exe.version", "$ver`n")
  return $how
}

function Install-MuZiggy {
  # uosc's helper for clipboard/OpenSubtitles on Windows; the uosc Lua sources are committed, only bin/ is ignored.
  param([hashtable]$Lock, [string]$VendorDir, [string]$ConfigDir)
  $ver = Get-MuLockValue $Lock 'UOSC_VERSION'
  $zip = Join-Path (Join-Path $VendorDir 'dl') "uosc-$ver.zip"
  $how = Save-MuVerified -Url (Get-MuLockValue $Lock 'UOSC_ZIP_URL') -Sha256 (Get-MuLockValue $Lock 'UOSC_ZIP_SHA256') -Dest $zip
  $dest = Join-Path (Join-Path (Join-Path $ConfigDir 'scripts') 'uosc') 'bin'
  $names = Expand-MuZipEntries -Zip $zip -Patterns @('scripts/uosc/bin/ziggy-windows.exe') -DestDir $dest
  if (@($names).Count -ne 1) { throw "uosc-$ver.zip no contiene scripts/uosc/bin/ziggy-windows.exe" }
  return $how
}

function Test-MuJsRuntime {
  # yt-dlp needs a JS runtime for YouTube: deno, or node >= 22 (docs/YTDLP.md §4).
  if (Get-Command -Name deno -CommandType Application -ErrorAction SilentlyContinue) { return $true }
  $node = Get-Command -Name node -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
  if ($node) {
    try {
      $v = [string](& $node.Path --version 2>$null)
      if ($v -match '^v?(\d+)' -and [int]$Matches[1] -ge 22) { return $true }
    } catch { }
  }
  return $false
}

function Install-MuDeno {
  param([hashtable]$Lock, [string]$VendorDir)
  $ver = Get-MuLockValue $Lock 'DENO_VERSION'
  $zip = Join-Path (Join-Path $VendorDir 'dl') "deno-$ver-x86_64-pc-windows-msvc.zip"
  $url = (Get-MuLockValue $Lock 'DENO_BASE_URL') + '/deno-x86_64-pc-windows-msvc.zip'
  $how = Save-MuVerified -Url $url -Sha256 (Get-MuLockValue $Lock 'DENO_SHA256_x86_64_windows') -Dest $zip
  $names = Expand-MuZipEntries -Zip $zip -Patterns @('deno.exe') -DestDir (Join-Path $VendorDir 'bin')
  if (@($names).Count -ne 1) { throw "$zip no contiene deno.exe" }
  return $how
}

function Install-MuWhisper {
  # Official whisper.cpp CPU build for x64 (release asset whisper-bin-x64.zip: Release\*.exe + DLLs) into
  # vendor\whisper\bin, where mpvd looks for whisper-cli(.exe). Models are downloaded by mpvd on first use.
  param([hashtable]$Lock, [string]$VendorDir)
  $ver = Get-MuLockValue $Lock 'WHISPER_WIN_VERSION'
  $zip = Join-Path (Join-Path $VendorDir 'dl') "whisper-bin-x64-$ver.zip"
  $how = Save-MuVerified -Url (Get-MuLockValue $Lock 'WHISPER_WIN_URL') -Sha256 (Get-MuLockValue $Lock 'WHISPER_WIN_SHA256') -Dest $zip
  $dest = Join-Path (Join-Path $VendorDir 'whisper') 'bin'
  $names = Expand-MuZipEntries -Zip $zip -Patterns @('Release/whisper-cli.exe', 'Release/whisper-server.exe', 'Release/*.dll') -DestDir $dest
  if (@($names) -notcontains 'whisper-cli.exe') { throw "$zip no contiene Release/whisper-cli.exe" }
  return $how
}

function Get-MuMpvVersion {
  # (major, minor) from `mpv --no-config --version`, or $null.
  param([string]$Mpv)
  try { $first = @(& $Mpv --no-config --version 2>$null)[0] } catch { return $null }
  if ([string]$first -match '^mpv v?(\d+)\.(\d+)') { return @([int]$Matches[1], [int]$Matches[2]) }
  return $null
}

function Get-MuLauncherText {
  # %LOCALAPPDATA%\MPV-UOS\bin\mpv-uos.cmd (ASCII: cmd.exe reads batch files in the OEM code page).
  param([string]$Root)
  $ps1 = Join-Path (Join-Path $Root 'bin') 'mpv-uos.ps1'
  return (@(
    '@echo off',
    "rem $MARK",
    "if exist `"$ps1`" goto run",
    "echo No encuentro MPV-UOS en `"$Root`": has movido la carpeta? Ejecuta tools\install.ps1 desde su nueva ubicacion. 1>&2",
    'exit /b 1',
    ':run',
    "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$ps1`" %*"
  ) -join "`r`n") + "`r`n"
}

function Get-MuPowerShellExe {
  # Windows PowerShell 5.1 ships with every Windows 10/11; its full path keeps shortcuts independent of PATH.
  if ($env:SystemRoot) { return (Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe') }
  return 'powershell.exe'
}

function Get-MuShellArguments {
  # What the Start menu shortcut and the mpv-uos:// handler run: hidden console, errors in a message box (-Gui).
  param([string]$Root, [switch]$WithUrl)
  $ps1 = Join-Path (Join-Path $Root 'bin') 'mpv-uos.ps1'
  $a = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$ps1`" -Gui"
  if ($WithUrl) { $a += ' "%1"' }
  return $a
}

# ---------------------------------------------------------------------------------------------------------------------
if ($MyInvocation.InvocationName -eq '.') { return }   # dot-sourced (tests): functions only

foreach ($r in @($Rest)) {
  if (-not $r) { continue }
  switch -Exact ($r) {
    '--uninstall' { $Uninstall = [switch]$true }
    '--dry-run' { $DryRun = [switch]$true }
    '--no-sync' { $NoSync = [switch]$true }
    '--no-vendor' { $NoVendor = [switch]$true }
    '--whisper' { $Whisper = [switch]$true }
    '--extras' { $Extras = [switch]$true }
    '--no-protocol' { $NoProtocol = [switch]$true }
    '--force' { $Force = [switch]$true }
    { $_ -in @('-h', '--help', '-?', '/?') } {
      Get-Content -LiteralPath $PSCommandPath -TotalCount 16 | ForEach-Object { $_ -replace '^# ?', '' }
      exit 0
    }
    default { [Console]::Error.WriteLine("opción desconocida: $r"); exit 2 }
  }
}

$OnWindows = Test-OnWindows
$Root = Split-Path -Parent $PSScriptRoot
$AppName = 'MPV-UOS'
$Folder = 'MPV-UOS'
try {
  $brand = Get-Content -Raw -LiteralPath (Join-Path $Root 'brand.json') | ConvertFrom-Json
  if ($brand.name) { $AppName = [string]$brand.name }
  if ($brand.folder) { $Folder = [string]$brand.folder }
} catch { }
if (-not $InstallDir) { $InstallDir = $env:MPV_UOS_INSTALL_DIR }
if (-not $InstallDir) {
  $base = $env:LOCALAPPDATA
  if (-not $base) { $base = [Environment]::GetFolderPath('LocalApplicationData') }
  $InstallDir = Join-Path $base $Folder
}
$StartMenuDir = $env:MPV_UOS_START_MENU_DIR
if (-not $StartMenuDir) { $StartMenuDir = [Environment]::GetFolderPath('Programs') }
if (-not $StartMenuDir) { $StartMenuDir = Join-Path $InstallDir 'Start Menu' }   # not Windows (tests)
$Launcher = Join-Path (Join-Path $InstallDir 'bin') 'mpv-uos.cmd'
$Shortcut = Join-Path $StartMenuDir "$AppName.lnk"
$StatePath = Join-Path $InstallDir 'install.json'
$VendorDir = Join-Path $Root 'vendor'
$LockPath = $env:MPV_UOS_VENDOR_LOCK
if (-not $LockPath) { $LockPath = Join-Path $Root 'vendor.lock' }

$script:Actions = New-Object System.Collections.ArrayList
$script:Failed = 0
function Say { param([string]$Text) Write-Host "• $Text" }
function Step {
  # Record an action; run it unless -DryRun. A failing step is reported and counted, the install goes on.
  param([string]$Action, [string]$Target, [string]$Detail = '', [scriptblock]$Do = $null)
  $null = $script:Actions.Add([ordered]@{ action = $Action; target = $Target; detail = $Detail })
  if ($DryRun -or $null -eq $Do) { return }
  try {
    $r = & $Do
    if ($r) { Say "  $Action`: $r" }
  } catch {
    $script:Failed++
    Write-Warning "$Action ($Target): $($_.Exception.Message)"
  }
}
function Finish {
  param([int]$Code)
  if ($DryRun) {
    $mode = 'install'
    if ($Uninstall) { $mode = 'uninstall' }
    [ordered]@{ mode = $mode; root = $Root; install_dir = $InstallDir; actions = @($script:Actions) } | ConvertTo-Json -Compress -Depth 5
  }
  exit $Code
}

function Read-MuState {
  if (Test-Path -LiteralPath $StatePath -PathType Leaf) {
    try { return (Get-Content -Raw -LiteralPath $StatePath | ConvertFrom-Json) } catch { }
  }
  return $null
}

# -- uninstall --------------------------------------------------------------------------------------------------------
if ($Uninstall) {
  # Only what this script created: the launcher carries the marker line, the shortcut must point to a
  # bin\mpv-uos.ps1 and be listed in install.json, the mpv-uos:// key carries the MPVUOSInstaller value.
  $state = Read-MuState
  if ((Test-Path -LiteralPath $Launcher -PathType Leaf)) {
    if ((Get-Content -Raw -LiteralPath $Launcher).Contains($MARK)) {
      Say "borrando $Launcher"
      Step 'remove-launcher' $Launcher '' { Remove-Item -Force -LiteralPath $Launcher }
    } else { Say "no es de MPV-UOS, se deja: $Launcher" }
  }
  $lnks = @($Shortcut)
  if ($state -and $state.PSObject.Properties['shortcut'] -and $state.shortcut) { $lnks += [string]$state.shortcut }
  foreach ($lnk in ($lnks | Select-Object -Unique)) {
    if (-not (Test-Path -LiteralPath $lnk -PathType Leaf)) { continue }
    $ours = $state -and $state.PSObject.Properties['shortcut'] -and ([string]$state.shortcut -eq $lnk)
    if ($ours -and $OnWindows) {
      try { $ours = (New-Object -ComObject WScript.Shell).CreateShortcut($lnk).Arguments -like '*mpv-uos.ps1*' } catch { $ours = $false }
    }
    if ($ours) {
      Say "borrando $lnk"
      Step 'remove-shortcut' $lnk '' { Remove-Item -Force -LiteralPath $lnk }
    } else { Say "no es de MPV-UOS, se deja: $lnk" }
  }
  if ($OnWindows -and (Test-Path -LiteralPath $PROTOCOL_KEY)) {
    $marker = (Get-ItemProperty -LiteralPath $PROTOCOL_KEY -ErrorAction SilentlyContinue).PSObject.Properties['MPVUOSInstaller']
    if ($marker -and $marker.Value -eq $MARK) {
      Say 'quitando los enlaces mpv-uos://'
      Step 'remove-protocol' $PROTOCOL_KEY '' { Remove-Item -Recurse -Force -LiteralPath $PROTOCOL_KEY }
    } else { Say "no es de MPV-UOS, se deja: $PROTOCOL_KEY" }
  }
  if (Test-Path -LiteralPath $StatePath -PathType Leaf) {
    Step 'remove-state' $StatePath '' { Remove-Item -Force -LiteralPath $StatePath }
  }
  Step 'remove-empty-dirs' $InstallDir '' {
    foreach ($d in @((Join-Path $InstallDir 'bin'), $InstallDir)) {
      if ((Test-Path -LiteralPath $d) -and -not (Get-ChildItem -Force -LiteralPath $d)) { Remove-Item -Force -LiteralPath $d }
    }
  }
  Say 'desinstalado (el checkout, vendor\ y los datos de usuario en %APPDATA%\mpv-uos no se tocan)'
  Finish 0
}

# -- requirements -----------------------------------------------------------------------------------------------------
$missing = @()
$mpv = Get-Command -Name mpv -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $mpv) { $missing += 'mpv (>= 0.41): winget install mpv  ·  o con scoop: scoop bucket add extras; scoop install mpv' }
foreach ($tool in @('ffmpeg', 'ffprobe')) {
  if (-not (Get-Command -Name $tool -CommandType Application -ErrorAction SilentlyContinue)) {
    $missing += "${tool}: winget install Gyan.FFmpeg  ·  o: scoop install ffmpeg"
  }
}
if (-not $NoSync -and -not (Get-Command -Name uv -CommandType Application -ErrorAction SilentlyContinue)) {
  $missing += 'uv: winget install astral-sh.uv  ·  o: https://docs.astral.sh/uv/'
}
if ($missing.Count -gt 0) {
  [Console]::Error.WriteLine('Faltan programas en el PATH:')
  foreach ($m in $missing) { [Console]::Error.WriteLine("  - $m") }
  [Console]::Error.WriteLine('Instálalos, abre una terminal nueva (para que se lea el PATH) y repite.')
  exit 1
}
$ver = Get-MuMpvVersion -Mpv $mpv.Path
if ($ver -and $ver[0] -eq 0 -and $ver[1] -lt 41) { Say "aviso: mpv $($ver[0]).$($ver[1]) < 0.41; algunas funciones no irán" }

# -- python env + vendored third parties ------------------------------------------------------------------------------
if (-not $NoSync) {
  $uvArgs = @('sync', '--project', $Root)
  if ($Extras) { $uvArgs += @('--extra', 'translate', '--extra', 'semantic', '--extra', 'impersonate') }
  Say ('uv ' + ($uvArgs -join ' '))
  Step 'uv-sync' $Root ($uvArgs -join ' ') {
    & uv @uvArgs
    if ($LASTEXITCODE -ne 0) { throw "uv sync terminó con código $LASTEXITCODE" }
  }
}
if (-not $NoVendor) {
  $lock = Read-MuVendorLock -Path $LockPath
  Say "binarios de terceros (vendor.lock, verificados con SHA-256) en $VendorDir"
  Step 'vendor-ziggy' (Join-Path $Root 'mpv-config\scripts\uosc\bin\ziggy-windows.exe') (Get-MuLockValue $lock 'UOSC_ZIP_URL') {
    Install-MuZiggy -Lock $lock -VendorDir $VendorDir -ConfigDir (Join-Path $Root 'mpv-config')
  }
  $ytBase = $env:MPV_UOS_YTDLP_BASE_URL
  Step 'vendor-yt-dlp' (Join-Path $VendorDir 'bin\yt-dlp.exe') ('yt-dlp ' + (Get-MuLockValue $lock 'YTDLP_VERSION') + ' + SHA2-256SUMS') {
    Install-MuYtDlp -Lock $lock -VendorDir $VendorDir -BaseUrl $ytBase -Force:$Force
  }
  if (Test-Path -LiteralPath (Join-Path $VendorDir 'bin\deno.exe') -PathType Leaf) {
    Say 'deno: presente (vendor\bin\deno.exe)'
  } elseif (Test-MuJsRuntime) {
    Say 'deno: no necesario (hay deno o node >= 22 en el PATH)'
  } else {
    Step 'vendor-deno' (Join-Path $VendorDir 'bin\deno.exe') (Get-MuLockValue $lock 'DENO_VERSION') {
      Install-MuDeno -Lock $lock -VendorDir $VendorDir
    }
  }
  if ($Whisper) {
    Step 'vendor-whisper' (Join-Path $VendorDir 'whisper\bin\whisper-cli.exe') (Get-MuLockValue $lock 'WHISPER_WIN_URL') {
      Install-MuWhisper -Lock $lock -VendorDir $VendorDir
    }
  }
}

# -- launcher, Start menu, mpv-uos:// ---------------------------------------------------------------------------------
if ((Test-Path -LiteralPath $Launcher -PathType Leaf) -and -not (Get-Content -Raw -LiteralPath $Launcher).Contains($MARK)) {
  [Console]::Error.WriteLine("Ya existe $Launcher y no lo creó MPV-UOS: no se sobrescribe (bórralo o usa -InstallDir).")
  exit 1
}
Say "lanzador $Launcher → $(Join-Path $Root 'bin\mpv-uos.ps1')"
Step 'write-launcher' $Launcher '' {
  $null = New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Launcher)
  [System.IO.File]::WriteAllText($Launcher, (Get-MuLauncherText -Root $Root), [System.Text.Encoding]::ASCII)
}

$psExe = Get-MuPowerShellExe
$lnkArgs = Get-MuShellArguments -Root $Root
Say "acceso directo del menú Inicio: $Shortcut"
Step 'create-shortcut' $Shortcut "$psExe $lnkArgs" {
  if (-not $OnWindows) { return 'omitido (no es Windows)' }
  $null = New-Item -ItemType Directory -Force -Path $StartMenuDir
  $ws = New-Object -ComObject WScript.Shell
  $s = $ws.CreateShortcut($Shortcut)
  $s.TargetPath = $psExe
  $s.Arguments = $lnkArgs
  $s.WorkingDirectory = $HOME
  $s.Description = "$AppName · reproductor multimedia"
  $s.WindowStyle = 7   # minimised: the hidden PowerShell only flashes briefly
  $s.IconLocation = "$($mpv.Path),0"
  $s.Save()
}

if (-not $NoProtocol) {
  $cmdLine = "`"$psExe`" " + (Get-MuShellArguments -Root $Root -WithUrl)
  Say 'enlaces mpv-uos:// (Mis notas, «Enviar a MPV-UOS» del navegador) → MPV-UOS'
  Step 'register-protocol' $PROTOCOL_KEY $cmdLine {
    if (-not $OnWindows) { return 'omitido (no es Windows)' }
    if (Test-Path -LiteralPath $PROTOCOL_KEY) {
      $marker = (Get-ItemProperty -LiteralPath $PROTOCOL_KEY -ErrorAction SilentlyContinue).PSObject.Properties['MPVUOSInstaller']
      if (-not ($marker -and $marker.Value -eq $MARK)) { return 'ya existe y no es de MPV-UOS: se deja' }
    }
    $null = New-Item -Force -Path "$PROTOCOL_KEY\shell\open\command"
    Set-ItemProperty -LiteralPath $PROTOCOL_KEY -Name '(default)' -Value "URL:$AppName"
    Set-ItemProperty -LiteralPath $PROTOCOL_KEY -Name 'URL Protocol' -Value ''
    Set-ItemProperty -LiteralPath $PROTOCOL_KEY -Name 'MPVUOSInstaller' -Value $MARK
    Set-ItemProperty -LiteralPath "$PROTOCOL_KEY\shell\open\command" -Name '(default)' -Value $cmdLine
  }
}

Step 'write-state' $StatePath '' {
  $state = [ordered]@{ marker = $MARK; root = $Root; launcher = $Launcher; shortcut = $Shortcut; protocol = (-not $NoProtocol) }
  [System.IO.File]::WriteAllText($StatePath, ($state | ConvertTo-Json -Depth 3))
}

Say "listo: busca $AppName en el menú Inicio, o añade $(Split-Path -Parent $Launcher) al PATH para usar 'mpv-uos <archivo|URL>'."
Say 'Desinstalar: tools\install.ps1 -Uninstall'
if ($script:Failed -gt 0) {
  Say "aviso: $($script:Failed) paso(s) fallaron (ver arriba); sin red, repite más tarde."
  Finish 1
}
Finish 0
